### ISSUE TITLE
Transfer repo to USDA/USFS GitHub

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/NRM-Grants-Agreements#141]
**Background**

Forest Service has an organization on Github.com as well as their internal Github Enterprise. We want to stay developing in the open, but this repo does need to move under FS control.

**We'll know we're done when...**
- [x] This repo lives under github.com/USDAForestService

**Tasks**
- [x] Talk to Aaron Burk to find out how to get our existing repo migrated to the FS organization.

**Comment by allisonnorman** [comment]
Hey @MelissaBraxton - Should we consider this for the next sprint? Do you have more context? Thanks!

**Comment by neilmb** [comment]
I'm working on this with the #admins-github slack channel and Chaochung Tsai at Forest Service.
