### ISSUE TITLE
Fieldsets duplicate on reload

### ISSUE THREAD

**Issue by tbaxter-18f** [USDAForestService/NRM-Grants-Agreements#195]
**Background**
An an admin grants change form, if you hit reload or take any other action that triggers a page reload, the fieldsets duplicate themselves, so there are multiple fields of the same name in the form. It appears to be related to how we add fieldsets for the change form. We have some indication using the `get_fieldsets` method may work better.

**We'll know we're done when...**
- [ ] Fieldsets stop duplicating themselves.
- [ ] 

**Tasks**
- [ ] 
- [ ]

**Comment by tbaxter-18f** [comment]
This was most likely resolved by the admin refactor. We haven't noticed it since, but we haven't confirmed, either. Might be a good issue to write a test for.

**Comment by beechnut** [comment]
This bug didn't reproduce for me after testing on quite a few (> 10) grant change forms. I'm concluding that it's resolved.

I'll add @tbaxter-18f's note about testing for this in #289.
