### ISSUE TITLE
Add draft proposal IDs to the list view

### ISSUE THREAD

**Issue by cmajel** [USDAForestService/NRM-Grants-Agreements#232]
**Background**
Currently, in the refactored prototype, you can see agreements in the system and click the agreement number to view its details. But, when you've created a new proposal, there is no agreement number, and it's not clear that the `-` is clickable
<img width="812" alt="list--proposal" src="https://user-images.githubusercontent.com/2374206/118292124-4f1fff80-b4a6-11eb-9553-6707dc320a77.png">
<img width="803" alt="list--agreement-number" src="https://user-images.githubusercontent.com/2374206/118292119-4deed280-b4a6-11eb-8d98-880c0355a75f.png">

Could we change the first column from `agreement number` to `agreement or proposal number` and populate it with whatever number we have available? Open to other ideas. 

**We'll know we're done when...**
- [ ] 
- [ ] 

**Tasks**
- [ ] 
- [ ]

**Comment by tbaxter-18f** [comment]
@MelissaBraxton we'll need to determine what we want to put there when an agreement ID has not yet been created.
* Proposal ID? Will that be confusing?
* "TBD"?
* something else?

**Comment by tbaxter-18f** [comment]
Resolved in this commit (https://github.com/USDAForestService/NRM-Grants-Agreements/commit/c83ff3f711ab487f49b18944c53ad61d86fbaba5)

I, um, accidentally committed to our main branch, but @neilmb was kind enough to give it a review in the commit.
