### ISSUE TITLE
Validate proposed start/end dates

### ISSUE THREAD

**Issue by tbaxter-18f** [USDAForestService/NRM-Grants-Agreements#233]
**Background**
We need to add some validation to proposed start /end dates to ensure data integrity:
* Proposed start date cannot be sooner than 48 days from today's date (as a going in position)
* Proposed end date cannot be before proposed start date
* 
**We'll know we're done when...**
- [ ] Validation is in place, and if a user tries to provide invalid dates an error is thrown.
- [ ] 

**Tasks**
- [ ] 
- [ ]

**Comment by allisonnorman** [comment]
Per @tbaxter-18f's suggestion, I combined this issue with #234. Closing this one as a duplicate.
