### ISSUE TITLE
Making date submitted and date received set for today

### ISSUE THREAD

**Issue by cmajel** [USDAForestService/NRM-Grants-Agreements#234]
**Background**
We need to add some validation to proposed start /end dates to ensure data integrity:

Proposed start date cannot be sooner than 48 days from today's date (as a going in position)
Proposed end date cannot be before proposed start date

Our understanding [based on conversations with Jamie ](https://docs.google.com/spreadsheets/d/1szcS652FZohhxkSPMNGnkPrj06uxSKqvC3ClL83ngsk/edit#gid=1044564396&range=B6)is that `date submitted` and `date received` are fields that are a part of the grants.gov / SF 424 feed. When a proposal is being created via the UI by FS staff, we believe these values can be set to today.

Here are the fields in the UI:
<img width="521" alt="Screen Shot 2021-05-14 at 10 39 29 AM" src="https://user-images.githubusercontent.com/2374206/118295391-c86d2180-b4a9-11eb-8c17-c74c479795f7.png">

Questions
* Can these be system generated?
* I think there's still things we need to learn about how the system ingests info from grants.gov, and what FS staff do with the information (#220) How would changes here affect that work?

**We'll know we're done when...**
- [ ] Validation is in place, and if a user tries to provide invalid dates an error is thrown.
- [ ] 

**Tasks**
- [ ] 
- [ ]

**Comment by tbaxter-18f** [comment]
@neilmb I had meant to knock this one out (and still may) but if I don't get to it, it'd be a good starter story.
