### ISSUE TITLE
Develop options doc for paths forward based on EFG funds

### ISSUE THREAD

**Issue by allisonnorman** [USDAForestService/NRM-Grants-Agreements#247]
**Background**
We've been talking about a few options for how to proceed based on the news that EFG will be redirected to 18F.

1. Pause now
2. Super slow burn
3. Go hard and pause in a few months reserving $ for post award mtmg
4. Go hard and trust there will be more money to extend our work for post award mgmt?

Let's document these options along with $, pros, and cons and share with the FS team for feedback on direction. 

**We'll know we're done when...**
- [ ] We've documented our thinking and included $s, possible dates, and pros/cons
- [ ] We've shared with the FS team. 

**Tasks**
- [ ] 
- [ ]

**Comment by neilmb** [comment]
Doc for this started in https://docs.google.com/document/d/1mrGS5dbg6fE6-NEUeEI1xmM0Bt8vxF00YlO41M3yE2I
