### ISSUE TITLE
Request outside-of-VPN access to app

### ISSUE THREAD

**Issue by tbaxter-18f** [USDAForestService/NRM-Grants-Agreements#262]
**Background**
The requirement that the entire app on AWS needs to be behind the VPN creates some complications:
* Juggling piv cards is kind of funky and annoying
* Some team members can't get a PIV card in anything resembling a timely fashion (August is the first available appointment)
* It effectively blocks us from bringing in short-term help via microrequests.

It would be very useful and productive if we could figure out how to open some access without the VPN. Maybe allow-listed IPs? Anything?

**We'll know we're done when...**
- [ ] 18F staff can access the app without having to be on the FS VPN
- [ ] 

**Tasks**
- [ ] Start a Teams discussion with Matt Reiss to see what can be done
- [ ]

**Comment by neilmb** [comment]
Started a Teams conversation on this topic.

**Comment by neilmb** [comment]
They need the site to be running on HTTPS first, then they can make it available outside of their VPN. They have submitted a request for an SSL Certificate for the application and hope to get the cert soon. Once that's installed, then they can make the site available publicly.

**Comment by neilmb** [comment]
Matt Reiss said on 6/1 that they should have the SSL cert in the next couple days and then their team can install it on the app and open up access off of the VPN.

**Comment by neilmb** [comment]
The SSL cert is installed and the site is working on HTTPS. I asked on Teams if Matt Reiss could now make it available without the VPN.

**Comment by neilmb** [comment]
Latest news from FS security office is that non-prod environments aren't allowed to be made available off of the FS VPN. From an email from Ross Willmot, the ISSO for the ATOed AWS environment:

> That is correct Matt.  Though restricting ports helps we’re not restricting access to the site.  I know this a dev environment but best practices dictate we restrict access to the site (FS VPN).

**Comment by neilmb** [comment]
This is finally resolved. The prototype environment is on the web at https://ga-dev.fs2c.usda.gov (note, you must use the "https" there). It is accessible from the Forest Service VPN as before, but it is ALSO accessible from the GSA VPN. So we can get our laptops on the GSA VPN and have access to the development environment.
