### ISSUE TITLE
Implement real Django-compatible server

### ISSUE THREAD

**Issue by tbaxter-18f** [USDAForestService/NRM-Grants-Agreements#78]
**Background**
For testing and prototyping, we're using Django's built-in Runserver. If this code is actually going to live beyond any trivial usage, that's inadequate and needs to be replaced by a real server.

**Acceptance criteria** 
- [ ] Real server is in place
- [ ] management command in Procfile uses new server

**Tasks**
- [ ] 
- [ ] 

**Definition of done**
- [ ]  
- [ ]

**Comment by neilmb** [comment]
Carter and I discussed using the `uwsgi` server. Should just be as easy as `pipenv install --save uwsgi` and then the command line from https://docs.djangoproject.com/en/3.2/howto/deployment/wsgi/uwsgi/ in the `Procfile`.

**Comment by tbaxter-18f** [comment]
I think until we're nearing prod, this is probably pretty low priority. @neilmb is there anything in the AWS move that makes it higher priority?

**Comment by neilmb** [comment]
No, not really. The AWS infrastructure is behind Nginx already, so I don't see any reason to change this soon.

**Comment by tbaxter-18f** [comment]
This would be good to do around the same time as #309

**Comment by neilmb** [comment]
The new Angular tech stack doesn't use any development servers outside of the local dev environment.
